importing the frameworks

In [1]:
import pandas as pd
import numpy
import tensorflow as tf

Preparing the data

In [2]:
df = pd.read_csv('./data/VAO_data.csv')
df.head()

,name,id,address,unom,district,area,col_758,col_759,col_760,col_761,...,col_766,col_769,col_770,col_771,col_772,col_775,col_781,col_1945_del,col_2463,col_3163
0,Адрес из сторонней системы,Идентификатор из сторонней системы,Адрес по БТИ,УНОМ,Округ,Район,Серии проектов,Количество этажей,Количество подъездов,Количество квартир,...,Износ объекта (по БТИ),Материалы стен,Признак аварийности здания,Количество пассажирских лифтов,Количество грузопассажирских лифтов,Очередность уборки кровли,Материалы кровли по БТИ,NaN,Типы жилищного фонда,Статусы МКД
1,"Дом по адресу РФ, г. Москва, вн.тер.г. м.о. Но...",1520521,"город Москва, Суздальская улица, дом 24, корпус 2",31783,Восточный административный округ,муниципальный округ Новокосино,2048785,14,3,130,...,NaN,2048929,22728486,6,0,NaN,22289207,0.0,42875644,58761330
2,"Дом по адресу РФ, г. Москва, вн.тер.г. м.о. Со...",1526496,"город Москва, улица Сокольнический Вал, дом 4",24231,Восточный административный округ,муниципальный округ Сокольники,2048912,5,3,61,...,NaN,179625090,22728486,0,0,22289162,22289201,0.0,42875644,58761330
3,"Дом по адресу РФ, г. Москва, вн.тер.г. м.о. Но...",1502303,"город Москва, Новокосинская улица, дом 38, кор...",16560,Восточный административный округ,муниципальный округ Новокосино,2048777,17,2,128,...,NaN,2048929,22728486,2,2,NaN,22289201,0.0,42875644,58761330
4,"Дом по адресу РФ, г. Москва, вн.тер.г. м.о. Ив...",1502774,"город Москва, Малый Купавенский проезд, дом 1",12180,Восточный административный округ,муниципальный округ Ивановское,2048789,16,2,206,...,NaN,179625089,22728486,2,2,NaN,22289201,0.0,42875644,58761330

In [3]:
def clean_df(df):
    df = df.drop(['name', 'id', 'address', 'unom', 'district', 'area', 'col_775', 'col_764', 'col_766', 'col_1945_del'], axis=1)
    df = df.drop([0], axis=0)
    df = df.rename(columns={'col_758': 'projects-series-number', 'col_759': 'floors-amount', 'col_760': 'entrances-amount', 
                            'col_761': 'apartments-amount', 'col_762': 'whole-square', 'col_763': 'apartments-square',	
                            'col_769': 'materials', 'col_770': 'EMERGENCY-RATE', 'col_771': 'passengers-elevators', 
                            'col_772': 'cargo-elevators', 'col_781': 'roof-materials',
                            'col_2463': 'housing-stock', 'col_3163': 'status'})
    return df
# df = numpy.where(df['col_770'] == '22728486', 0, 1)
df = clean_df(df)
df

,projects-series-number,floors-amount,entrances-amount,apartments-amount,whole-square,apartments-square,materials,EMERGENCY-RATE,passengers-elevators,cargo-elevators,roof-materials,housing-stock,status
1,2048785,14,3,130,9210.9,8615.3,2048929,22728486,6,0,22289207,42875644,58761330
2,2048912,5,3,61,2806.9,2603.3,179625090,22728486,0,0,22289201,42875644,58761330
3,2048777,17,2,128,9538.4,6990.9,2048929,22728486,2,2,22289201,42875644,58761330
4,2048789,16,2,206,11502.2,10480.4,179625089,22728486,2,2,22289201,42875644,58761330
5,2048912,5,9,155,9140,6932,179625102,22728486,0,0,22289205,42875644,58761330
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4368,2048912,5,3,60,2973.4,2476.5,179625102,22728486,0,0,22289205,42875644,58761330
4369,2048798,5,5,70,6041,5045,179625102,22728486,0,0,22289204,42875644,58761330
4370,2048878,15,3,123,12627.8,11894,179625111,22728486,3,3,22289201,42875644,58761330
4371,2048798,14,1,112,5462.6,5440.5,179625102,22728486,1,1,22289201,42875644,58761330
4372,2048912,5,2,41,2340,2130,179625102,22728486,0,0,22289204,42875644,58761330

In [4]:
train, valid, test = numpy.split(df.sample(frac=1), [int(0.6 * len(df)), int(0.8 * len(df))])

d:\progdata\anaconda\envs\ml\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [5]:
def scale_dataset(data):
    data['EMERGENCY-RATE'] = (data['EMERGENCY-RATE'] == '22728488').astype(int)
    y = numpy.array(data[data.columns[7]].values)
    X = numpy.array(data.drop(data.columns[7], axis=1).values)
    data = numpy.array(numpy.hstack((X, numpy.reshape(y, (-1, 1)))))
    
    return data.astype(float), X.astype(float), y.astype(float)

In [6]:
train_data, X_train, y_train = scale_dataset(train)
valid_data, X_valid, y_valid = scale_dataset(valid)
test_data, X_test, y_test = scale_dataset(train)

In [11]:
def normalize(dataset):
    return tf.keras.utils.normalize(dataset)

In [12]:
X_train = normalize(X_train)
X_test = normalize(X_test)
X_valid = normalize(X_valid)

X_train

array([[1.05019840e-02, 7.17643102e-08, 5.12602215e-09, ...,
        1.14254938e-01, 2.19781501e-01, 3.01211879e-01],
       [1.05027676e-02, 2.56301091e-08, 1.02520436e-08, ...,
        1.14254946e-01, 2.19781486e-01, 3.01211859e-01],
       [2.69096351e-02, 2.88963370e-07, 2.62693973e-08, ...,
        2.92761938e-01, 5.63158664e-01, 7.71812362e-01],
       ...,
       [1.05027676e-02, 2.56301091e-08, 1.53780654e-08, ...,
        1.14254946e-01, 2.19781486e-01, 3.01211859e-01],
       [1.05027676e-02, 2.56301090e-08, 5.12602181e-08, ...,
        1.14254946e-01, 2.19781486e-01, 3.01211859e-01],
       [1.05021828e-02, 1.02520432e-07, 1.53780648e-08, ...,
        1.14254925e-01, 2.19781477e-01, 3.01211846e-01]])